server:
  port: 18080
  log:
    path: logs

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )

logging:
  level:
    root: debug

files:
  uploaded-path: /Users/bean/Development/OhMwoMuc/OhMwoMucFiles

jwt:
  atk-expired-time: 1800
  rtk-expired-time: 1209600
